# Generated by Django 5.2 on 2025-04-24 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_avatar_customuser_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='subscription_active',
            field=models.BooleanField(default=False, verbose_name='Начало подписки'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='subscription_end',
            field=models.DateField(blank=True, null=True, verbose_name='Конец подписки'),
        ),
    ]
