# Generated by Django 5.1 on 2025-04-25 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_managers'),
        ('accounts', '0006_alter_customuser_first_name'),
    ]

    operations = [
    ]
