# Generated by Django 5.1 on 2025-04-25 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_merge_20250425_1035'),
        ('recipes', '0011_alter_ingredient_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='prefers',
            field=models.ManyToManyField(blank=True, null=True, to='recipes.tag', verbose_name='Предпочтения'),
        ),
    ]
