# Generated by Django 5.2 on 2025-04-25 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_customuser_prefers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='subscription_active',
            field=models.BooleanField(default=False, verbose_name='Активна ли подписка'),
        ),
    ]
