# Generated by Django 5.2 on 2025-04-25 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_customuser_subscription_active'),
        ('recipes', '0011_alter_ingredient_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='prefers',
            field=models.ManyToManyField(blank=True, to='recipes.tag', verbose_name='Предпочтения'),
        ),
    ]
