# Generated by Django 5.2 on 2025-04-25 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0011_alter_customuser_prefers"),
        ("recipes", "0011_alter_ingredient_unit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="prefers",
            field=models.ManyToManyField(
                blank=True, to="recipes.tag", verbose_name="Предпочтения"
            ),
        ),
    ]
