# Generated by Django 3.2.20 on 2025-04-21 19:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_type', models.CharField(choices=[('classic', 'Классическое'), ('low_carb', 'Низкоуглеводное'), ('vegetarian', 'Вегетарианское'), ('keto', 'Кето')], max_length=50, verbose_name='Тип меню')),
                ('duration', models.PositiveSmallIntegerField(choices=[(1, '1 месяц'), (3, '3 месяца'), (6, '6 месяцев'), (12, '12 месяцев')], default=1, verbose_name='Срок подписки')),
                ('include_breakfast', models.BooleanField(default=True, verbose_name='Завтраки')),
                ('include_lunch', models.BooleanField(default=True, verbose_name='Обеды')),
                ('include_dinner', models.BooleanField(default=True, verbose_name='Ужины')),
                ('include_dessert', models.BooleanField(default=True, verbose_name='Десерты')),
                ('persons_count', models.PositiveSmallIntegerField(default=1, verbose_name='Количество персон')),
                ('exclude_fish', models.BooleanField(default=False, verbose_name='Исключить рыбу и морепродукты')),
                ('exclude_meat', models.BooleanField(default=False, verbose_name='Исключить мясо')),
                ('exclude_grains', models.BooleanField(default=False, verbose_name='Исключить зерновые')),
                ('exclude_honey', models.BooleanField(default=False, verbose_name='Исключить продукты пчеловодства')),
                ('exclude_nuts', models.BooleanField(default=False, verbose_name='Исключить орехи и бобовые')),
                ('exclude_dairy', models.BooleanField(default=False, verbose_name='Исключить молочные продукты')),
                ('start_date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата начала')),
                ('end_date', models.DateField(verbose_name='Дата окончания')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Подписка',
                'verbose_name_plural': 'Подписки',
            },
        ),
    ]
