# Generated by Django 5.2 on 2025-04-24 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0002_subscription_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscription",
            name="menu_type",
            field=models.CharField(
                choices=[
                    ("classic", "Классическое"),
                    ("low_carb", "Низкоуглеводное"),
                    ("vegetarian", "Вегетарианское"),
                    ("keto", "Кето"),
                    ("vegan", "Веганское"),
                ],
                max_length=50,
                verbose_name="Тип меню",
            ),
        ),
    ]
