# Generated by Django 5.2 on 2025-04-25 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0003_alter_subscription_menu_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscription",
            name="duration",
            field=models.PositiveSmallIntegerField(
                choices=[(1, "1 месяц")], default=1, verbose_name="Срок подписки"
            ),
        ),
    ]
