# Generated by Django 5.2 on 2025-04-26 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0004_alter_subscription_duration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscription",
            name="menu_type",
            field=models.CharField(
                choices=[
                    ("classic", "Классическое"),
                    ("low", "Низкоуглеводное"),
                    ("veg", "Вегетарианское"),
                    ("keto", "Кето"),
                ],
                max_length=50,
                verbose_name="Тип меню",
            ),
        ),
    ]
