# Generated by Django 5.1 on 2025-04-23 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='imgae',
            field=models.ImageField(default='', upload_to='', verbose_name='Картинка'),
            preserve_default=False,
        ),
    ]
