# Generated by Django 5.1 on 2025-04-23 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_alter_recipe_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='imgae',
            new_name='image',
        ),
    ]
