# Generated by Django 5.1 on 2025-04-24 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_dailymenu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='unit',
            field=models.CharField(choices=[('g', 'г'), ('ml', 'мл'), ('pcs', 'шт'), ('pkg', 'упаковка')], max_length=3),
        ),
    ]
