# Generated by Django 5.1 on 2025-04-25 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0010_alter_ingredient_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='unit',
            field=models.CharField(choices=[('g', 'г'), ('ml', 'мл'), ('pcs', 'шт'), ('pkg', 'упаков')], max_length=3),
        ),
    ]
