# Generated by Django 5.1 on 2025-04-25 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0011_alter_ingredient_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailymenu',
            name='change_count',
            field=models.IntegerField(default=3, verbose_name='Количество изменений блюд'),
        ),
    ]
