# Generated by Django 5.2 on 2025-04-25 16:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Allergy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_type', models.CharField(choices=[('classic', 'Классическое'), ('low', 'Низкоуглеводное'), ('veg', 'Вегетарианское'), ('keto', 'Кето')], max_length=20, verbose_name='Тип меню')),
                ('duration', models.PositiveSmallIntegerField(verbose_name='Срок (месяцев)')),
                ('include_breakfast', models.BooleanField(default=True, verbose_name='Завтраки')),
                ('include_lunch', models.BooleanField(default=True, verbose_name='Обеды')),
                ('include_dinner', models.BooleanField(default=True, verbose_name='Ужины')),
                ('include_dessert', models.BooleanField(default=True, verbose_name='Десерты')),
                ('persons', models.PositiveSmallIntegerField(default=1, verbose_name='Количество персон')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Оплачен')),
                ('allergies', models.ManyToManyField(blank=True, to='order.allergy', verbose_name='Аллергии')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
    ]
