# Generated by Django 5.2 on 2025-04-26 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0001_initial"),
        ("subscriptions", "0005_alter_subscription_menu_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="subscription",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="subscriptions.subscription",
            ),
        ),
    ]
