# Generated by Django 5.2 on 2025-04-26 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата изменения'),
        ),
        migrations.AlterField(
            model_name='order',
            name='duration',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Срок (месяцев)'),
        ),
    ]
