# Generated by Django 5.2 on 2025-04-26 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order_updated_at_alter_order_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='allergies',
            field=models.ManyToManyField(blank=True, to='order.allergy', verbose_name='Предпочтения'),
        ),
    ]
