# Generated by Django 5.2 on 2025-04-26 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_order_allergies'),
        ('recipes', '0012_dailymenu_change_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='prefers',
            field=models.ManyToManyField(blank=True, to='recipes.tag', verbose_name='Предпочтения'),
        ),
    ]
