# Generated by Django 5.2 on 2025-04-26 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_order_prefers'),
        ('recipes', '0012_dailymenu_change_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='prefers',
            field=models.ManyToManyField(blank=True, to='recipes.tag', verbose_name='Предпоч'),
        ),
    ]
