# Generated by Django 5.2 on 2025-04-27 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_alter_order_prefers'),
        ('recipes', '0013_tag_category_alter_ingredient_calories_per_unit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='menu_slug',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='orders_tags', to='recipes.tag', verbose_name='Теги'),
        ),
        migrations.AlterField(
            model_name='order',
            name='duration',
            field=models.PositiveSmallIntegerField(blank=True, default=1, null=True, verbose_name='Срок (месяцев)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='persons',
            field=models.PositiveSmallIntegerField(blank=True, default=1, null=True, verbose_name='Количество персон'),
        ),
    ]
